### ISSUE TITLE
`add_require': undefined method `add_require' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dreamcat4** [mislav/hanna#11] opened 2009-10-15 17:25 UTC
id@janitors-Mac-mini:tmp/yamldoc ‹master*›$ gem install mislav-hanna
Successfully installed rdoc-2.3.0
Successfully installed haml-2.0.10
Successfully installed mislav-hanna-0.1.11
3 gems installed
Installing ri documentation for rdoc-2.3.0...
Installing ri documentation for haml-2.0.10...
Installing ri documentation for mislav-hanna-0.1.11...

RDoc failure in lib/rubygems_plugin.rb at or around line 12 column
36

Before reporting this, could you check that the file you're documenting
compiles cleanly--RDoc is not a full Ruby parser, and gets confused easily if
fed invalid programs.

The internal error was:

/Users/id/.gem/ruby/active/gems/rdoc-2.3.0/lib/rdoc/code_objects.rb:411:in `add_require': undefined method`add_require' for nil:NilClass (NoMethodError)
    from /Users/id/.gem/ruby/active/gems/rdoc-2.3.0/lib/rdoc/parser/ruby.rb:2321:in `parse_require'
    from /Users/id/.gem/ruby/active/gems/rdoc-2.3.0/lib/rdoc/parser/ruby.rb:2455:in`parse_statements'
    from /Users/id/.gem/ruby/active/gems/rdoc-2.3.0/lib/rdoc/parser/ruby.rb:2208:in `parse_method'

**Comment by dreamcat4** [comment] 2009-10-15 17:59
Installs quietly (no error) with these arguments:

 gem install mislav-hanna  --no-rdoc --no-ri 

Solved.

**Comment by dreamcat4** [comment] 2009-10-15 18:05
Issue Closed.

**Comment by mislav** [comment] 2009-10-15 23:44
Thanks, but duplicate of #9. Closing

**Closed as completed by mislav** 2009-10-15 23:44 UTC
Labels: duplicate
